[project]
name = "telecom"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pika>=1.3.2",
    "sqlmodel>=0.0.31",
]


[tool.uv.workspace]
members = ["common/packages/*", "services/*"]
exclude = ["common/packages/seeds"]


