[project]
name = "metric-ingestion-models"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tung leduc", email = "chopperman259@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
